// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gffixqjrxsahcfcktpec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmZml4cWpyeHNhaGNmY2t0cGVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTA5MzIsImV4cCI6MjA3MDY2NjkzMn0.G3NeCPeXDo2WTF7KsRckONC0b17NIaFhtYelNQfsesU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});